copy resolv.conf

diff --git a/vpn-tunnel b/vpn-tunnel
--- a/vpn-tunnel
+++ b/vpn-tunnel
@@ -107,6 +107,11 @@ openvpn_invocation_server () {
 	"--secret $(quote "$keyfile_server") $usergroup"
 }
 
+# an ID we're using to identify our resources (vpn-tunnel instance)
+client_hash () {
+    openvpn_invocation_client stable | sha1sum | awk '{print $1}'
+}
+
 
 # The code generated by masq_code is run on the *server*
 
@@ -136,8 +141,6 @@ iptables_AD () {
     iptables -t nat "$AD" POSTROUTING -m mark --mark 1 \
 	-j SNAT --to-source "$clientlocalip"
 }
-
-#çXXX don't forget DNS  copy  of resolv.conf.
 
 
 start () {
@@ -227,16 +230,23 @@ start () {
 	    i=$(( $i - 1 ))
 	fi
     done
-    if [ "$ok" -eq 1 ]; then
-
-	=== cleanup
-	rm -f "$keyfile_client"
-	ssh "$sshserver" "rm -f \"$keyfile_server\""
-
-	===.
-    else
+    if [ "$ok" -eq 0 ]; then
+	echo "could not get ping reply" >&2
 	false
     fi
+
+    === "cleanup"
+    rm -f "$keyfile_client"
+    ssh "$sshserver" "rm -f \"$keyfile_server\""
+    
+    === "copy over /etc/resolv.conf"
+    tmp=`tempfile -d /etc/`
+    ssh "$sshserver" 'cat /etc/resolv.conf' > "$tmp"
+    chmod a+r "$tmp"
+    mv /etc/resolv.conf /etc/resolv.conf.$(client_hash)
+    mv "$tmp" /etc/resolv.conf
+
+    ===.
 }
 
 stop () {
@@ -261,6 +271,8 @@ stop () {
 	ip route add $dfltroute
     fi
 
+    === "restore /etc/resolv.conf"
+    mv /etc/resolv.conf.$(client_hash) /etc/resolv.conf || true
 
     === "stop openvpn on server"
     ssh "$sshserver" 'set -eu
